on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Run lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v5.1.1
        with:
           python-version: '3.12'
      - name: "Get repository code"
        uses: actions/checkout@v4
      - name: "Install libraries"
        run: "pip install -r requirements.txt"
      - name: "Run Pylint"
        run: |
          pylint *.py --fail-under=8
          echo 'all linting complete.'